VICTORY_POINTS = 12

MAIN_BOARD_SQUARES = 13, 11
PLAYER_BOARD_SQUARES = 6, 1
CHOICE_BOARD_SQUARES = 5, 3

CARD_IMG_SIZE_SMALL = 120, 120
CARD_IMG_SPACING = 2
BIG_SPACE = 30
PILE_COUNT = 5

BUTTON_BOARD_SQUARES = 1, 6
BUTTON_SIZE = 60, 60

PATHS_COUNT = 7
TOWNS_COUNT = 7
VILLAGES_COUNT = 5

BACKGROUND_IMAGE = (240, 220, 200)

CARD_IMG_SIZE_BIG = 480, 480

MAX_LAND_RESOURCES = 3

RESOURCE_LIST = ['gold', 'rock', 'sheep', 'wood', 'brick', 'grain']
CARDS_INCREASING_HAND_CNT = ['library', 'cloister']
ADVANCE_BUILDINGS = ['cloister', 'library']   # university
BROWSE_DISCOUNT_BUILDINGS = ['town_hall']
STOLEN_AMBUSH_RESOURCES = ['rock', 'sheep']
CIVIL_WAR_PROTECTION = ['church']

AMBUSH_MAX_RESOURCES = 7
